double? h;
double? w;
const String uri = "http://localhost:4040";
const String illustration1 = 'assets/images/queer-hero.png';
const String logo = 'assets/images/logo.png';
const String ribbon = 'images/Ribbon.png';
const String ribbon2 = 'images/Ribbon-2.png';
const String image1 = 'images/image1.png';
const String image2 = 'images/image2.png';
const String image3 = 'images/image3.png';
const String jobIcon = 'images/jobs.png';
const String scholarIcon = 'images/scholarship.png';
const String trainingIcon = 'images/training.png';
